sudo: false

language: php

env:
    global:
        - COMPOSER_ARGS_NO_INTERACTION=""
        - COMPOSER_ARGS_IGNORE_PLATFORM=""

matrix:
    include:
        - php: 5.5
          env:
              - DEPS=lowest
        - php: 5.5
          env:
              - DEPS=locked
        - php: 5.6
          env:
              - DEPS=lowest
        - php: 5.6
          env:
              - DEPS=locked
              - TEST_COVERAGE=true
        - php: 7.0
          env:
              - DEPS=lowest
        - php: 7.0
          env:
              - DEPS=locked
        - php: 7.0
          env:
              - DEPS=latest
        - php: 7.1
          env:
              - DEPS=lowest
        - php: 7.1
          env:
              - DEPS=locked
        - php: 7.1
          env:
              - DEPS=latest
    
before_install:
    - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0; fi
    - composer self-update
    
install:
    - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction --ignore-platform-reqs ; fi
    - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --prefer-stable --no-interaction ; fi
    - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-interaction --ignore-platform-reqs satooshi/php-coveralls:^1.0 ; fi
    - travis_retry composer install --no-interaction --ignore-platform-reqs
 
script:
    - ./vendor/bin/phpunit --configuration phpunit.xml.dist test

after_script:
    - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/coveralls ; fi
